[package]
name = "soundmod-natives"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.135"
rodio = {version = "0.16.0",features=["symphonia","symphonia-vorbis"]}